baseurl: /
title: TRAFO kunstnerhus
defaultContentLanguage: nb
languages:
  nb:
    languageName: Norsk
    weight: 1
  en:
    languageName: English
    weight: 2
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
params:
  images: img/
  antallAtelier: "37"
  styreMail: styret@trafokunstnerhus.no
markup:
  goldmark:
    renderer:
      unsafe: true
      safehtml: true
